### ISSUE TITLE
Seek problem

### ISSUE THREAD

**Issue by Media182** [Teranode/jw-provider#7]
Getting this error when seeking the video (strangely happens when seek 2nd seek):
type: 'networkError', details: 'fragLoadError', fatal: true, frag: e, response: 'Cancel segment request: simultaneous segment requests are not supported'
and this cause JW Player Error 233000 (An unknown media loading error occurred.) and player fails.

Had this with 8.24 and now have it with 8.26 version.

Seems this error goes from p2p-media-loader-hlsjs.min.js - I'm using it cause JW fails to load with your provider.hlsjs.js and default Novage version.

**Comment by Denoder** [comment]
I no longer provide updates for p2p-media-loader-hlsjs.min.js

**Comment by Media182** [comment]
But have you tested your 8.26.0 provider.hlsjs.js with default loader JS files?
https://cdn.jsdelivr.net/npm/p2p-media-loader-core@latest/build/p2p-media-loader-core.min.js
https://cdn.jsdelivr.net/npm/p2p-media-loader-hlsjs@latest/build/p2p-media-loader-hlsjs.min.js

I can't play the video using provider.hlsjs.js + ones above.

**Comment by Denoder** [comment]
I'm aware of it, however I'd have to make some modifications to that core and I'm not looking to do so. The repository itself has lacked recent updates so this repository only serves as a way to use hls.js as an external package.

**Comment by ghost** [comment]
@Media182 i have same problem when use there library js. @Teranode do you have solution for it?
https://cdn.jsdelivr.net/npm/p2p-media-loader-core@latest/build/p2p-media-loader-core.min.js
https://cdn.jsdelivr.net/gh/teranode/jw-provider@latest/p2p-media-loader-hlsjs.min.js
https://cdn.jsdelivr.net/gh/teranode/jw-provider@latest/provider.hlsjs.js
https://ssl.p.jwpcdn.com/player/v/8.26.1/jwplayer.js

**Comment by ghost** [comment]
@Teranode hello, https://cdn.jsdelivr.net/gh/teranode/jw-provider@latest/provider.hlsjs.js not working with jwplayer v8.26.1. can you fix it?
